/*
 * This file is generated by jOOQ.
 */
package src.main.java.com.jnutz.jooq.public_;

import src.main.java.com.jnutz.jooq.public_.tables.Employees;
import src.main.java.com.jnutz.jooq.public_.tables.Ingredients;
import src.main.java.com.jnutz.jooq.public_.tables.Items;
import src.main.java.com.jnutz.jooq.public_.tables.Users;

import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables
{
    
    /**
     * The table <code>PUBLIC.Employees</code>.
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;
    
    /**
     * The table <code>PUBLIC.Ingredients</code>.
     */
    public static final Ingredients INGREDIENTS = Ingredients.INGREDIENTS;
    
    /**
     * The table <code>PUBLIC.Items</code>.
     */
    public static final Items ITEMS = Items.ITEMS;
    
    /**
     * The table <code>PUBLIC.Users</code>.
     */
    public static final Users USERS = Users.USERS;
}
