/*
 * This file is generated by jOOQ.
 */
package src.main.java.com.jnutz.jooq.public_;

import src.main.java.com.jnutz.jooq.public_.tables.*;

import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables
{
    
    /**
     * The table <code>PUBLIC.Ingredients</code>.
     */
    public static final Ingredients INGREDIENTS = Ingredients.INGREDIENTS;
    
    /**
     * The table <code>PUBLIC.Items</code>.
     */
    public static final Items ITEMS = Items.ITEMS;
    
    /**
     * The table <code>PUBLIC.Recipe_Ingredients</code>.
     */
    public static final RecipeIngredients RECIPE_INGREDIENTS = RecipeIngredients.RECIPE_INGREDIENTS;
    
    /**
     * The table <code>PUBLIC.Recipe_Steps</code>.
     */
    public static final RecipeSteps RECIPE_STEPS = RecipeSteps.RECIPE_STEPS;
    
    /**
     * The table <code>PUBLIC.Recipes</code>.
     */
    public static final Recipes RECIPES = Recipes.RECIPES;
    
    /**
     * The table <code>PUBLIC.Steps</code>.
     */
    public static final Steps STEPS = Steps.STEPS;
    
    /**
     * The table <code>PUBLIC.Users</code>.
     */
    public static final Users USERS = Users.USERS;
}
