/*
 * This file is generated by jOOQ.
 */
package src.main.java.com.jnutz.jooq.public_;


import javax.annotation.processing.Generated;

import src.main.java.com.jnutz.jooq.public_.tables.Users;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.Users</code>.
     */
    public static final Users USERS = Users.USERS;
}
