/*
 * This file is generated by jOOQ.
 */
package src.main.java.com.jnutz.jooq.public_.tables.records;


import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import src.main.java.com.jnutz.jooq.public_.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record4<Short, String, byte[], byte[]> {

    private static final long serialVersionUID = 1606377243;

    /**
     * Setter for <code>PUBLIC.Users.UserID</code>.
     */
    public void setUserid(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.Users.UserID</code>.
     */
    public Short getUserid() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>PUBLIC.Users.Username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.Users.Username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.Users.Salt</code>.
     */
    public void setSalt(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.Users.Salt</code>.
     */
    public byte[] getSalt() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>PUBLIC.Users.Password</code>.
     */
    public void setPassword(byte... value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.Users.Password</code>.
     */
    public byte[] getPassword() {
        return (byte[]) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Short, String, byte[], byte[]> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Short, String, byte[], byte[]> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Short> field1() {
        return Users.USERS.USERID;
    }

    @Override
    public Field<String> field2() {
        return Users.USERS.USERNAME;
    }

    @Override
    public Field<byte[]> field3() {
        return Users.USERS.SALT;
    }

    @Override
    public Field<byte[]> field4() {
        return Users.USERS.PASSWORD;
    }

    @Override
    public Short component1() {
        return getUserid();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public byte[] component3() {
        return getSalt();
    }

    @Override
    public byte[] component4() {
        return getPassword();
    }

    @Override
    public Short value1() {
        return getUserid();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public byte[] value3() {
        return getSalt();
    }

    @Override
    public byte[] value4() {
        return getPassword();
    }

    @Override
    public UsersRecord value1(Short value) {
        setUserid(value);
        return this;
    }

    @Override
    public UsersRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UsersRecord value3(byte... value) {
        setSalt(value);
        return this;
    }

    @Override
    public UsersRecord value4(byte... value) {
        setPassword(value);
        return this;
    }

    @Override
    public UsersRecord values(Short value1, String value2, byte[] value3, byte[] value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Short userid, String username, byte[] salt, byte[] password) {
        super(Users.USERS);

        set(0, userid);
        set(1, username);
        set(2, salt);
        set(3, password);
    }
}
